-- 手工验证：产生 DML/DDL，挖出来，观察记录结构。以 SYSDBA 执行。
-- 实测结果全部记录在 docs/research/dm-test-instance-findings.md。
--
-- ⚠️ disql 用法注意（踩过的坑）：
--   1. 语句里的 CREATE SCHEMA 会开启一个块，必须用单独一行的 / 收尾，否则后面所有语句都被吞掉。
--   2. 通过 stdin 灌脚本时文件必须是 LF 换行；CRLF 会让 `;` 失效。

-- === 1. 记录起始位点 ===
SELECT CUR_LSN, FILE_LSN, FLUSH_LSN FROM V$RLOG;

-- === 2. 产生变更 ===
INSERT INTO CDC_TEST.T_BASIC (ID,C_TINY,C_BIGINT,C_DEC,C_DOUBLE,C_CHAR,C_VARCHAR,C_DATE,C_TIME,C_TS,C_TSTZ) VALUES (1,1,9223372036854775807,1234.5678,3.14159,'abc','一段中文',DATE '2026-01-02',TIME '10:20:30',TIMESTAMP '2026-01-02 10:20:30.123456',TIMESTAMP '2026-01-02 10:20:30.123456 +08:00');
INSERT INTO CDC_TEST.T_BASIC (ID,C_VARCHAR) VALUES (2,NULL);
COMMIT;
UPDATE CDC_TEST.T_BASIC SET C_VARCHAR='改过了', C_DEC=9999.0001 WHERE ID=1;
COMMIT;
DELETE FROM CDC_TEST.T_BASIC WHERE ID=2;
COMMIT;

-- 无主键表：看 sqlRedo 的 WHERE 怎么定位行
INSERT INTO CDC_TEST.T_NO_PK VALUES (1,'x');
COMMIT;
UPDATE CDC_TEST.T_NO_PK SET B='y' WHERE A=1;
COMMIT;

-- LOB：小值内联，大值只给占位符
INSERT INTO CDC_TEST.T_LOB (ID,C_CLOB,C_BLOB,C_TEXT) VALUES (2,'short clob',0x0102,'short text');
INSERT INTO CDC_TEST.T_LOB (ID,C_CLOB,C_BLOB) VALUES (3, LPAD('a',3000,'b'), 0x03);
COMMIT;

-- 多语句事务：看事务边界怎么体现
INSERT INTO CDC_TEST.T_COMPOSITE_PK VALUES (1,'a','v1');
INSERT INTO CDC_TEST.T_COMPOSITE_PK VALUES (1,'b','v2');
UPDATE CDC_TEST.T_COMPOSITE_PK SET V='v3' WHERE K1=1 AND K2='a';
COMMIT;

-- 回滚的事务：COMMITTED_DATA_ONLY 下不应出现在挖掘结果里
INSERT INTO CDC_TEST.T_COMPOSITE_PK VALUES (2,'z','rolled-back');
ROLLBACK;

-- DDL
ALTER TABLE CDC_TEST.T_BASIC ADD COLUMN C_NEW VARCHAR(30);
CREATE TABLE CDC_TEST.T_DDL_PROBE (ID INT PRIMARY KEY, V VARCHAR(10));
DROP TABLE CDC_TEST.T_DDL_PROBE;

SELECT CUR_LSN FROM V$RLOG;

-- === 3. 看归档文件 ===
-- 实测：**不需要**强制切换，ACTIVE（当前正在写）的归档文件就能挖到刚提交的数据。
-- 若要主动切换（会新建一个归档文件）：ALTER SYSTEM ARCHIVE LOG CURRENT; —— 实测可用。
SELECT PATH, STATUS, ARCH_LSN, CLSN, CREATE_TIME, CLOSE_TIME FROM V$ARCH_FILE ORDER BY ARCH_LSN;

-- === 4. 挖掘 ===
-- 把上一步查到的归档文件路径填进去（ACTIVE 的那个也行）。
DBMS_LOGMNR.ADD_LOGFILE('<归档文件绝对路径>');
-- 2130 = 2(COMMITTED_DATA_ONLY) + 16 + 64 + 2048
DBMS_LOGMNR.START_LOGMNR(OPTIONS => 2130);

SELECT SCN, XID, OPERATION_CODE, OPERATION, SEG_OWNER, TABLE_NAME, SQL_REDO, SQL_UNDO
  FROM V$LOGMNR_CONTENTS
 ORDER BY SCN;

DBMS_LOGMNR.END_LOGMNR();
